from typing import Any

def bubble(arr: Any) -> None: ...
def heap(arr: Any) -> None: ...
def insertion(arr: Any) -> None: ...
def intro(arr: Any) -> None: ...
def merge(arr: Any) -> None: ...
def par_merge(arr: Any) -> None: ...
def par_sort(arr: Any) -> None: ...
def par_sort_unstable(arr: Any) -> None: ...
def pdq(arr: Any) -> None: ...
def quick(arr: Any) -> None: ...
def radix(arr: Any) -> None: ...
def smart(arr: Any) -> None: ...
def tim(arr: Any) -> None: ...
